name: crm_task_manager
description: "A new Flutter project."

version: 2.1.89+116


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.5
  shared_preferences: ^2.3.5
  intl: ^0.20.2 
  open_file: ^3.5.9
  path_provider: ^2.1.5
  dropdown_search: ^6.0.2
  dart_pusher_channels: ^1.2.3
  social_media_recorder: ^1.2.1
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.2.9
  flutter_background: ^1.3.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  chat_bubbles: ^1.6.0
  just_audio: ^0.9.18
  audioplayers: ^6.1.0
  file_picker: ^10.3.3
  voice_message_package:
    git:
      url: https://github.com/noolfj/voice_message_playerCustom.git
  # ffmpeg_kit_flutter: ^6.0.3
  http_parser: ^4.0.2
  flutter_unfocuser: ^1.0.0
  infinite_scroll_pagination: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  radio_group_v2: ^3.2.1
  animated_custom_dropdown: ^3.1.1
  flutter_svg: ^2.0.16
  image_gallery_saver_plus: ^4.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  local_auth: ^2.3.0
  vibration: ^2.0.1
  device_info_plus: ^11.1.1
  image_picker: ^1.2.0
  app_tracking_transparency: ^2.0.6+1
  url_launcher: ^6.3.1
  flutter_localization: ^0.3.1
  restart_app: ^1.3.2
  scrollable_positioned_list: ^0.3.8
  auto_size_text: ^3.0.0
  flutter_contacts: ^1.1.9+2
  tutorial_coach_mark: ^1.2.13
  reorderables: ^0.6.0
  table_calendar: ^3.2.0
  cached_network_image: ^3.4.1
  mobile_scanner: ^7.0.1
  connectivity_plus: ^6.1.4
  permission_handler: ^11.4.0
  photo_view: ^0.15.0
  new_version_plus: ^0.1.1
  package_info_plus: ^8.1.1

  flutter_html: ^3.0.0
  flutter_quill: ^11.4.2
  audio_service: ^0.18.18
  audio_metadata_reader: ^1.4.2
  flutter_slidable: ^4.0.1
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  build_runner: ^2.8.0
  # home_widget: ^0.8.1


  
  
bottom_navy_bar:
  path: lib/widgets/bottom_navy_bar.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  #  ios: true
  image: assets/icons/playstore.png

flutter:

  uses-material-design: true

  assets:
    - assets/icons/MyNavBar/
    - assets/icons/AppBar/
    - assets/icons/Profile/
    - assets/icons/Dashboard/
    - assets/icons/tabBar/
    - assets/icons/leads/
    - assets/icons/chats/
    - assets/icons/chats/menu_icons/pin.svg
    - assets/icons/history.png
    - assets/icons/history2.png
    - assets/icons/chats/menu_icons/pin_list.svg
    - assets/icons/chats/menu_icons/edit.svg
    - assets/icons/chats/menu_icons/delete.svg
    - assets/icons/chats/menu_icons/delete-red.svg
    - assets/icons/chats/menu_icons/reply.svg
    - assets/icons/chats/menu_icons/copy.svg
    - assets/icons/chats/menu_icons/open.svg
    - assets/icons/1c/
    - assets/icons/
    - assets/icons/shamCRM.jpg
    - assets/images/
    - assets/images/avatar2.png
    - assets/icons/languages/
    - assets/langs/
    - assets/icons/icon-fire-color.png
    - assets/icons/icon-fire-no-color.png
    - assets/icons/files/apk.png
    - assets/icons/files/csv.png
    - assets/icons/files/docx.png
    - assets/icons/files/doc.png
    - assets/icons/files/exe.png
    - assets/icons/files/gif.png
    - assets/icons/files/jpg.png
    - assets/icons/files/pdf.png
    - assets/icons/files/png.png
    - assets/icons/files/svg.png
    - assets/icons/files/txt.png
    - assets/icons/files/xls.png
    - assets/icons/files/zip.png
    - assets/icons/files/add.png
    - assets/icons/files/file.png
    - assets/icons/files/ppt.png
    - assets/icons/files/pptx.png
    - assets/icons/Profile/support_chat.png
    - assets/audio/
    - assets/page_2/icons/
    - assets/audio/voice_operator.mp3
    - assets/icons/MyNavBar/money_ON.png


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
    - family: Golos
      fonts:
        - asset: assets/fonts/Golos-Regular.ttf
        - asset: assets/fonts/Golos-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

dependency_overrides:
  intl: ^0.20.2  
